<?php
/**
 * @package     add-to-homescreen
 * @author      NexPWA <hello@nexpwa.com>
 * @license     https://opensource.org/licenses/OSL-3.0 Open Software License v. 3.0 (OSL-3.0)
 * @link        http://www.nexpwa.com/
 * @copyright   Copyright © 2020 Codilar Technologies Pvt. Ltd.. All rights reserved
 */
?>
<?php
/** @var \NexPWA\AddToHomescreen\Block\PwaLinks $block */
$version = time();
$manifestUrl = $block->getBaseUrl() . 'version' . $version . '/manifest.webmanifest';
$serviceWorkerUrl = $block->getBaseUrl() . 'service-worker.js';
?>
<?php if ($block->isManifestEnabled()): ?>
    <link rel="manifest" href="<?php echo $manifestUrl ?>">
<?php endif; ?>

<?php if ($block->isServiceWorkerEnabled()): ?>
    <script type="text/javascript">
        (function (w) {
            if ('serviceWorker' in w.navigator) {
                w.navigator.serviceWorker.register('<?php echo $serviceWorkerUrl ?>');
            }
        })(window);
    </script>
<?php endif; ?>
